### ISSUE TITLE
A release supporting scala 2.13 ? (for expression-parser)

### ISSUE THREAD

**Issue by erinmez** [hypertino/binders#5]
Hi @maqdev & @horse315, 
This issue rather concerns expression-parser but I'm not able to raise a ticket there. Any chance that you guys could make a release for scala 2.13.1 ? I have quickly looked into it and have noticed that it depends on parboiled, which supports 2.13, but also depends on hypertino binders, which in turn depends on hypertino inflector.
Thx, Tanju

**Comment by maqdev** [comment]
@erinmez thanks for reporting, I'll look into that

**Comment by erinmez** [comment]
Hi there, first of all, happy new year 🎉  Do you guys have an update on making a release for scala 2.13?

**Comment by maqdev** [comment]
Hey @erinmez 
I've released both `binders` v `1.3.0` and `expression-parser` v `0.3.0` for Scala 2.13

**Comment by erinmez** [comment]
Thanks a lot @maqdev  🎉
